### ISSUE TITLE
Touch screen not working

### ISSUE THREAD

**Issue by hamzaarbeed** [Meetoul/twrp_device_Unihertz_Jelly2#1]
Hello,
Thank you for your efforts.

Touch screen is not working in twrp. I flashed alpha 03 recovery.
my phone is tee. build is Unihertz_Jelly2_20210417
I tried all the releases. no luck.
I erased recovery and flashed twrp. 
The same issue.

**Comment by Meetoul** [comment]
Hi!

Could you please provide dmesg (`adb shell dmesg`) from recovery?

**Comment by hamzaarbeed** [comment]
Here it is.
[New Text Document.TXT](https://github.com/Meetoul/twrp_device_Unihertz_Jelly2/files/6777723/New.Text.Document.TXT)

Thank you

**Comment by Meetoul** [comment]
Thanks for providing the logs. I see that there is some strange I2C error during touch panel initialization. 

Does touch works on stock ROM? If yes, could you please tell which ROM do you use?

It looks like some kind of physical issue or your Jelly2 has different touch panel, idk... 

```
[    2.294291]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_init_work_callback:964] MediaTek touch panel driver init
[    2.295060]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_probe:727] enter tpd_probe, 727
[    2.295147]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_get_gpio_info:255] [tpd -1] mt_tpd_pinctrl+++++++++++++++++
[    2.295314]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_get_gpio_info:265] Cannot find pinctrl default -19!
[    2.295330]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_get_gpio_info:301] [tpd-1] mt_tpd_pinctrl----------
[    2.295351]  (2)[97:kworker/u16:1]<<GTP-INF>>[tpd_local_init:935] regulator_get
[    2.295402]  (2)[97:kworker/u16:1]mtk-tpd touch: touch supply vtouch not found, using dummy regulator
[    2.295524]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_output:228] tpd_gpio_output pin = 0, level = 0
[    2.295552]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_output:228] tpd_gpio_output pin = 1, level = 0
[    2.295877]  (0)[1:swapper/0]mt-rtc mt-rtc: setting system clock to 2021-07-07 13:49:51 UTC (1625665791)
[    2.312645]  (2)[97:kworker/u16:1]<<GTP-DBG>>[gt1x_power_switch:430]Power switch on!
[    2.312659]  (2)[97:kworker/u16:1]<<GTP-ERR>>[gt1x_power_switch:436] regulator_set_voltage() failed!
[    2.312670]  (2)[97:kworker/u16:1]<<GTP-INF>>[gt1x_reset_guitar:926] GTP RESET!
[    2.312680]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_output:228] tpd_gpio_output pin = 0, level = 0
[    2.312698]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_output:228] tpd_gpio_output pin = 1, level = 0
[    2.324647]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_output:228] tpd_gpio_output pin = 0, level = 1
[    2.352653]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_output:228] tpd_gpio_output pin = 1, level = 0
[    2.412654]  (2)[97:kworker/u16:1]mtk-tpd:[tpd_gpio_as_int:219] [tpd] tpd_gpio_as_int
[    2.412677]  (2)[97:kworker/u16:1]<<GTP-DBG>>[gt1x_set_reset_status:816]Set reset status.
[    2.412774]  (2)[97:kworker/u16:1]i2c i2c-0: error:addr=0x5d,irq_stat=0x3,ch_offset=0x0,mask:0x12f      <---- I2C error start
[    2.412788]  (2)[97:kworker/u16:1]i2c_dump_info: +++++++++++++++++++
[    2.412807]  (2)[97:kworker/u16:1]I2C structure:
[    2.412807] [I2C]Clk=24960000,Id=0,Op=0x1,Irq_stat=0x3,Total_len=0x5
[    2.412807] [I2C]Trans_len=0x5,Trans_num=0x1,Trans_auxlen=0x0,
[    2.412807] [I2C]speed=400000,Trans_stop=1,cg_cnt=1,hs_only=1,
[    2.412807] [I2C]ch_offset=0x0,ch_offset_default=0x0
[    2.412829]  (2)[97:kworker/u16:1]base addr:0x000000007fc41740
[    2.412854]  (2)[97:kworker/u16:1]I2C register:
[    2.412854] [I2C]SLAVE_ADDR=0xba,INTR_MASK=0x0,INTR_STAT=0x0,
[    2.412854] [I2C]CONTROL=0x28,TRANSFER_LEN=0x5,TRANSAC_LEN=0x1,
[    2.412854] [I2C]DELAY_LEN=0xa,TIMING=0x405,LTIMING=0x23,START=0x0
[    2.412854] [I2C]FIFO_STAT=0x1,IO_CONFIG=0x3,HS=0x0
[    2.412854] [I2C]DCM_EN=0x0,DEBUGSTAT=0x300,EXT_CONF=0x1801
[    2.412854] [I2C]TRANSFER_LEN_AUX=0x1
```

**Comment by hamzaarbeed** [comment]
The touch works on stock rom. I have the most recent stock rom for non european. t is 20210519
this is the link for it. https://drive.google.com/file/d/1dmW5TFj56WAz2YgTHHQDXkrknmeKYg-r/view?usp=drivesdk

I also had an issue with the touch screen when  i tried to root the device with modified boot image with magisk. I flashed the boot image . after that the touch screen didn't work. So I unbricked the device by flashing the most recent stock rom using SP flash tool. And the touch screen is working again. And I rooted the device using magisk modified boot img. the boot image I extracted from the most recent stock image.
Now I have jelly 2 rooted with magisk and the most recent image.

If you want me to run adb shell dmesg on stock rom let me know.

**Comment by Meetoul** [comment]
Hmm.. I use the same ROM.

Yeah, dmesg from stock ROM will help me to determine what touch driver is really used.

Also, you can use USB mouse instead of touch screen. Before I fixed the touch, I've been using USB type C male - type A female adapter and USB mouse, it completely works in recovery.

**Comment by hamzaarbeed** [comment]
Do you suggest me to flash certain partitions again to have the drivers working properly?
Here is dmseg of stock rom
[New Text Document (2).TXT](https://github.com/Meetoul/twrp_device_Unihertz_Jelly2/files/6780581/New.Text.Document.2.TXT)

**Comment by Meetoul** [comment]
Wow, according to the logs our Jellies really have the different touch screens (and different drivers).

Here is dmesg log from my Jelly:

`[  516.143735] (1)[285:mtk-tpd]<<GTP-DBG>>[gt1x_touch_event_handler:1484]Released Touch.`

Here is from yours:

`[24498.558597] ←[0m(2)[288:mtk-tpd]<<GTP-DBG>>[gt1151qm_touch_event_handler:1484]Released Touch.`

I need some to investigate how to get your touch working in recovery. I will notify once I find something (or give up).

Could you please provide me a dmesg log just after the boot? Kernel initialization logs will be useful for me.

**Comment by Meetoul** [comment]
Also, could you please follow these steps:
```
adb shell
su
echo 0 > /proc/sys/kernel/kptr_restrict
sysctl -w kernel.randomize_va_space=0
cat /proc/kallsyms >/sdcard/symbl.txt
exit
exit
adb pull /sdcard/symbl.txt
```
and provide me the resulting symbl.txt file?

**Comment by hamzaarbeed** [comment]
ok thank you so much
Here is symbl.txt
i did this while the phone was in stock rom
[symbl.txt](https://github.com/Meetoul/twrp_device_Unihertz_Jelly2/files/6796298/symbl.txt)

For the dmesg after the boot. is it as soon as i see the logo of unihertz?
This is what I got when I put the commands as soon as I saw the logo while booting
[New Text Document (3).TXT](https://github.com/Meetoul/twrp_device_Unihertz_Jelly2/files/6796305/New.Text.Document.3.TXT)

**Comment by Meetoul** [comment]
Thank you for providing the dmesg and symbl.txt. I'll analyze them and come back to you with the result.

**Comment by Meetoul** [comment]
@hamzaarbeed 

Please check the following:

[recovery.zip](https://github.com/Meetoul/twrp_device_Unihertz_Jelly2/files/6806568/recovery.zip)

**Comment by hamzaarbeed** [comment]
Wow it's working. Thank you so much. You are amazing.

**Comment by Meetoul** [comment]
Good to hear.

Thank you too, it would be impossible without your help and patience.

**Comment by hamzaarbeed** [comment]
Now, I want to try Lineage os 18 that you posted on xda forum, do you think the touch screen will work or the rom needs to be modified to work? Thank you kind sir

**Comment by Meetoul** [comment]
Patching kernel to make touch work is required only for recovery mode. Android ROMs work on unmodified kernel, so it will work for you.
